// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class AboutAppController : UIViewController
	{
		public AboutAppController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewWillAppear (bool animated)
		{

			this.ScrollableArea.Frame= ((AppDelegate)UIApplication.SharedApplication.Delegate).Window.Frame;
			this.ScrollableArea.ContentSize=new SizeF (320, 600);

			this.BackgroundView.Image = UIImage.FromFile ("./Assets/bgr.png");
			this.Facebook.SetBackgroundImage (UIImage.FromFile ("./Assets/FacebookGrey.png"), UIControlState.Normal);
			this.Twitter.SetBackgroundImage (UIImage.FromFile ("./Assets/TwitterGrey.png"), UIControlState.Normal);
			this.GooglePlus.SetBackgroundImage (UIImage.FromFile ("./Assets/GooglePlusGrey.png"), UIControlState.Normal);
			this.WriteReview.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
			this.NavigationController.SetNavigationBarHidden (false, false);

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

		}
	}
}