// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class AccountSettingsController : UIViewController
	{

		public AccountSettingsController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			this.ScrollableArea.Frame= ((AppDelegate)UIApplication.SharedApplication.Delegate).Window.Frame;
			this.ScrollableArea.ContentSize=new SizeF (320, 600);
			if (((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto == null) {
				this.Image.Image = UIImage.FromFile ("./Assets/profilebig.png");
			} else {
				this.Image.Image = ((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto;
			}
			this.editProfile.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.changePassword.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.notifications.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.contentLang.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.removeAcc.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.aboutApp.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.signOut.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			AppDelegate appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;
			UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);

			this.editProfile.TouchUpInside += (object sender, EventArgs e) => {
				EditProfileController edit = (EditProfileController)board.InstantiateViewController ("editProfileController");
				this.NavigationController.PushViewController(edit, true);
			};

			this.changePassword.TouchUpInside += (object sender, EventArgs e) => {
				ChangePasswordController changePass = (ChangePasswordController)board.InstantiateViewController ("changePasswordConreoller");
				this.NavigationController.PushViewController(changePass, true);
			};



			this.notifications.TouchUpInside += (object sender, EventArgs e) => {
				NotificationsController	notification = (NotificationsController)board.InstantiateViewController("notificationsController");
				this.NavigationController.PushViewController(notification, true);
			};

			this.contentLang.TouchUpInside += (object sender, EventArgs e) => {
				ContentLanguageController contentLang = (ContentLanguageController)board.InstantiateViewController ("contetntLangController");
				this.NavigationController.PushViewController(contentLang, true);
			};

			this.removeAcc.TouchUpInside += (object sender, EventArgs e) => {
				RemoveAccountController removeAcc = (RemoveAccountController)board.InstantiateViewController ("removeAccController");
				this.NavigationController.PushViewController(removeAcc, true);
			};

			this.aboutApp.TouchUpInside += (object sender, EventArgs e) => {
				AboutAppController aboutApp = (AboutAppController)board.InstantiateViewController ("aboutAppController");
				this.NavigationController.PushViewController(aboutApp, true);
			};



			this.signOut.TouchUpInside += (object sender, EventArgs e) => {
				//WelcomeController welcome = (WelcomeController)board.InstantiateViewController ("welcomecontroller");
			
			};

		}
	}
}