// This file has been autogenerated from a class added in the UI designer.

	using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;

namespace SportNet
{
	public partial class ChangePasswordController : UIViewController
	{
		public ChangePasswordController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			this.Change.SetBackgroundImage(UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);
			this.Divider.Image = UIImage.FromFile ("./Assets/divider.png");

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
			this.NavigationController.SetNavigationBarHidden (false, false);

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.CurrentPassword.ShouldReturn += (textField) => { 
				textField.ResignFirstResponder();
				return true; 
			};
			this.NewPassword.ShouldReturn += (textField) => { 
				textField.ResignFirstResponder();
				return true; 
			};
			this.ConfirmPassword.ShouldReturn += (textField) => { 
				textField.ResignFirstResponder();
				return true; 
			};






		}
	}
}