// This file has been autogenerated from a class added in the UI designer.

	using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;

namespace SportNet
{
	public partial class EditProfileController : UIViewController
	{
		public EditProfileController (IntPtr handle) : base (handle)
		{
		}
		UIImagePickerController imagePicker;

		public override void ViewWillAppear (bool animated)
		{
			this.ScrollableArea.Frame= ((AppDelegate)UIApplication.SharedApplication.Delegate).Window.Frame;
			this.ScrollableArea.ContentSize=new SizeF (320, 600);

			if (((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto == null) {
				this.Image.Image = UIImage.FromFile ("./Assets/profilebig.png");
			} else {
				this.Image.Image = ((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto;
			}

			this.MakeProfilePublic.SetBackgroundImage(UIImage.FromFile ("./Assets/settings-unchecked.png"), UIControlState.Normal);
			this.Chose.SetBackgroundImage(UIImage.FromFile ("./Assets/choose.png"), UIControlState.Normal);
			this.Divider.Image = UIImage.FromFile("./Assets/divider.png");
			this.SecondDivider.Image = UIImage.FromFile ("./Assets/divider.png");

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
			this.NavigationController.SetNavigationBarHidden (false, false);


		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.Chose.TouchUpInside += (s, e) => {
				// create a new picker controller
				imagePicker = new UIImagePickerController ();

				// set our source to the photo library
				imagePicker.SourceType = UIImagePickerControllerSourceType.PhotoLibrary;

				// set what media types
				imagePicker.MediaTypes = UIImagePickerController.AvailableMediaTypes (UIImagePickerControllerSourceType.PhotoLibrary);

				imagePicker.FinishedPickingMedia += Handle_FinishedPickingMedia;
				imagePicker.Canceled += Handle_Canceled;

				// show the picker
				NavigationController.PresentViewController(imagePicker, true,null);


			};

		}
		// Do something when the 
		void Handle_Canceled (object sender, EventArgs e) {
			Console.WriteLine ("picker cancelled");
			imagePicker.DismissViewController(true,null);
		}

		// This is a sample method that handles the FinishedPickingMediaEvent
		protected void Handle_FinishedPickingMedia (object sender, UIImagePickerMediaPickedEventArgs e)
		{
			// determine what was selected, video or image
			bool isImage = false;
			switch(e.Info[UIImagePickerController.MediaType].ToString())
			{
				case "public.image":
				Console.WriteLine("Image selected");
				isImage = true;
				break;

				case "public.video":
				Console.WriteLine("Video selected");
				break;
			}

			Console.Write("Reference URL: [" + UIImagePickerController.ReferenceUrl + "]");

			// get common info (shared between images and video)
			NSUrl referenceURL = e.Info[new NSString("UIImagePickerControllerReferenceUrl")] as NSUrl;
			if (referenceURL != null) 
				Console.WriteLine(referenceURL.ToString ());

			// if it was an image, get the other image info
			if(isImage) {

				// get the original image
				UIImage originalImage = e.Info[UIImagePickerController.OriginalImage] as UIImage;
				if(originalImage != null) {
					// do something with the image
					Console.WriteLine ("got the original image");
					((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto = originalImage;
				}

				// get the edited image
				UIImage editedImage = e.Info[UIImagePickerController.EditedImage] as UIImage;
				if(editedImage != null) {
					// do something with the image
					Console.WriteLine ("got the edited image");
					((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto = editedImage;
				}

				//- get the image metadata
				NSDictionary imageMetadata = e.Info[UIImagePickerController.MediaMetadata] as NSDictionary;
				if(imageMetadata != null) {
					// do something with the metadata
					Console.WriteLine ("got image metadata");
				}

			}
			// if it's a video
			else {
				// get video url
				NSUrl mediaURL = e.Info[UIImagePickerController.MediaURL] as NSUrl;
				if(mediaURL != null) {
					//
					Console.WriteLine(mediaURL.ToString());
				}
			}

			// dismiss the picker
			imagePicker.DismissViewController(true,null);
		}
	}
}