// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using System.Collections.Generic;
using System.Linq;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Newtonsoft.Json;
using SportNet.Web.Models;

namespace SportNet
{
	public partial class HomeController : UITableViewController
	{
		private UIRefreshControl refresh;
		private UIActivityIndicatorView spinner;

		public UIActivityIndicatorView Spinner 
		{
			get {
				return spinner;
			}
		}

		public HomeController (IntPtr handle) : base (handle)
		{
			spinner = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge);
			spinner.Center = new PointF (160, 160);
			spinner.HidesWhenStopped = true;
			TableView.AddSubview (spinner);
			spinner.StartAnimating ();
		}

		private void getData()
		{
			var request = new RestRequest ();
			request.RequestFinished += (object sender, RequestEndedArgs e) => {
				InvokeOnMainThread(delegate {
					var data = (CategoryModel)JsonConvert.DeserializeObject(e.Result, typeof(CategoryModel));
					var menuController = (MenuController)((MainTabController)UIApplication.SharedApplication.Delegate.Window.RootViewController).News.MenuViewLeft;

					var featured = (List<NewsModelItem>)data.News;
					featured = featured.Where(c => !string.IsNullOrEmpty(c.Img)).Take(4).ToList();

					TableView.Source = new HomeControllerSource(featured, data.Categories);
					menuController.TableView.Source = new MenuControllerSource(data.Categories, "news");
					menuController.TableView.ReloadData();
					TableView.ReloadData();
					spinner.StopAnimating();
				});
			};
			request.Send (string.Format(RequestConfig.News(), 0, 0), "GET");
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			refresh = new UIRefreshControl ();
			TableView.AddSubview (refresh);
			refresh.ValueChanged += (object sender, EventArgs e) => {
				getData();
				refresh.EndRefreshing();
			};

			TableView.ScrollsToTop = true;
			getData ();
		}
	}
}
