// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class LiveScoreController : UINavigationController
	{
		public LiveScoreController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

		}
		public override void ViewWillAppear (bool animated)
		{

		
		}
	}
}
