// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class LiveScoreCell : UITableViewCell
	{
		public UILabel teamOne;
		public UILabel teamTwo;
		public UILabel result;
		public UILabel timeIndicator;
		public UIImageView loader;
		public UILabel hyphen;
		public UIImageView separatingLine;

		public LiveScoreCell (NSString cellId) : base(UITableViewCellStyle.Default, cellId)
		{
			SelectionStyle = UITableViewCellSelectionStyle.None;

			base.LayoutSubviews ();

			hyphen = new UILabel ();
			hyphen.Text = "-";
			hyphen.TextColor = UIColor.White;
			hyphen.TextAlignment = UITextAlignment.Center;
			hyphen.BackgroundColor = UIColor.Clear;

			teamOne = new UILabel ();
			teamOne.TextColor = UIColor.White;
			teamOne.Font = UIFont.FromName ("Helvetica-Bold", 12f);
			teamOne.BackgroundColor = UIColor.Clear;
			teamOne.Lines = 2;

			teamTwo = new UILabel ();
			teamTwo.TextColor = UIColor.White;
			teamTwo.Font = UIFont.FromName ("Helvetica-Bold", 12f);
			teamTwo.BackgroundColor = UIColor.Clear;
			teamTwo.Lines = 2;

			timeIndicator = new UILabel ();
			timeIndicator.TextColor = UIColor.FromRGB (102, 102, 102);
			timeIndicator.Font = UIFont.FromName ("Helvetica", 12f);
			timeIndicator.BackgroundColor = UIColor.Clear;

			loader = new UIImageView ();
			loader.ContentMode = UIViewContentMode.ScaleAspectFill;
			loader.ClipsToBounds = true;

			result = new UILabel ();
			result.TextColor = UIColor.White;
			result.Font = UIFont.FromName ("Helvetica-Bold", 12f);
			result.BackgroundColor = UIColor.Clear;

			separatingLine = new UIImageView ();
			separatingLine.ContentMode = UIViewContentMode.ScaleAspectFill;
			separatingLine.ClipsToBounds = true;



			ContentView.Add (teamOne);
			ContentView.Add (teamTwo);
			ContentView.Add (hyphen);
			ContentView.Add (result);
			ContentView.Add (loader);
			ContentView.Add (result);
			ContentView.Add (timeIndicator);
			ContentView.Add (separatingLine);


		}

		public void SetLiveScoreCell(string teamOne,string teamTwo, string result, string image,int minute,string starttime)
		{
			this.teamOne.Text = teamOne;
			this.teamTwo.Text = teamTwo;
			this.result.Text = result;
			if (minute == -1) {
				this.timeIndicator.Text = "Finished";
				this.timeIndicator.TextColor = UIColor.FromRGB (102, 102, 102);
				this.loader.Hidden = true;
			} else if (minute == 0) {
				this.timeIndicator.Text = starttime;
				this.timeIndicator.TextColor = UIColor.FromRGB (102, 102, 102);
				this.result.Text="";
				this.loader.Hidden = true;
			} else {
				this.timeIndicator.TextColor = UIColor.Red;
				this.timeIndicator.Text = string.Format("{0}'", minute);
				this.loader.Image = UIImage.FromFile ("./Assets/indicator.png");
				this.loader.Hidden = false;
			}
			this.separatingLine.Image = UIImage.FromFile ("./Assets/divider.png");
		}

		public override void LayoutSubviews ()
		{
			this.ContentView.BackgroundColor = UIColor.FromRGB (26, 26, 26);
			timeIndicator.Frame = new RectangleF (8, 15, 50, 16);  
			loader.Frame = new RectangleF(33, 12, 22, 22);
	
			teamOne.SizeToFit ();
			float maxTeamOneWidth = Math.Min (teamOne.Frame.Width, (ContentView.Bounds.Width - 135) / 2);
			teamOne.Frame = new RectangleF(68, 15,maxTeamOneWidth, 16);
			teamOne.SizeToFit ();
			hyphen.Frame = new RectangleF (68+maxTeamOneWidth, 15, 15, 16);
			teamTwo.SizeToFit ();
			float maxTeamTwoWidth = Math.Min (teamTwo.Frame.Width, (ContentView.Bounds.Width - 135) / 2);
			teamTwo.Frame = new RectangleF(68+maxTeamOneWidth+15, 15, maxTeamTwoWidth, 16);
			teamTwo.SizeToFit ();
			result.Frame = new RectangleF(ContentView.Bounds.Width-80, 18, 40, 12);

			separatingLine.Frame = new RectangleF (0,ContentView.Bounds.Height - 1, 285, 1);

		}
	}
}
