// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class LoginController : UIViewController
	{
		public LoginController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			this.Email.Background = UIImage.FromFile ("./Assets/input.png");
			this.Password.Background = UIImage.FromFile ("./Assets/input.png");
			this.Facebook.SetBackgroundImage (UIImage.FromFile ("./Assets/facebook.png"), UIControlState.Normal);
			this.Twitter.SetBackgroundImage (UIImage.FromFile ("./Assets/twitter.png"), UIControlState.Normal);
			this.GooglePlus.SetBackgroundImage (UIImage.FromFile ("./Assets/google.png"), UIControlState.Normal);
			this.Login.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);

			this.Email.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.Email.LeftViewMode = UITextFieldViewMode.Always;
			this.Password.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.Password.LeftViewMode = UITextFieldViewMode.Always;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
			this.NavigationController.SetNavigationBarHidden (false, false);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.ForgotPassword.TouchUpInside += (object sender, EventArgs e) => {
				var board = UIStoryboard.FromName ("MainStoryboard", null);
				var password = (ForgotPasswordController)board.InstantiateViewController ("forgotpassword");
				this.NavigationController.PushViewController(password, true);
			};

			this.Login.TouchUpInside += (object sender, EventArgs e) => {
				((UIWindow)UIApplication.SharedApplication.Delegate.Window).RootViewController = 
					new MainTabController();
			};
		}
	}
}
