// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class MenuController : UITableViewController
	{
		public MenuController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			this.Image.Image = UIImage.FromFile ("./Assets/profile.png");
			this.AddContent.SetBackgroundImage (UIImage.FromFile ("./Assets/addcontent.png"), UIControlState.Normal);
			var cats = new string[] { "Football", "Basketball", "Golf", "Formula 1", "Poker", "More" };
			TableView.Source = new MenuControllerSource (cats);
			TableView.ScrollsToTop = false;
			TableView.SeparatorColor = UIColor.FromRGB (38, 38, 38);
			TableView.AllowsMultipleSelection = false;
		}
	}
}
