// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class MenuController : UITableViewController
	{
		public MenuController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			if (((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto == null) {
				this.Image.Image = UIImage.FromFile ("./Assets/profile.png");
			} else {
				this.Image.Image = ((AppDelegate)UIApplication.SharedApplication.Delegate).profilePhoto;
			}
			this.AddContent.SetBackgroundImage (UIImage.FromFile ("./Assets/addcontent.png"), UIControlState.Normal);
			var cats = new string[] { "Football", "Basketball", "Golf", "Formula 1", "Poker", "More" };
			TableView.Source = new MenuControllerSource (cats);
			TableView.ScrollsToTop = false;
			TableView.SeparatorColor = UIColor.FromRGB (38, 38, 38);
			TableView.AllowsMultipleSelection = false;
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			AppDelegate appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;
			UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);


			this.Settings.TouchUpInside += (object sender, EventArgs e) => {
				AccountSettingsController accSettings = (AccountSettingsController)board.InstantiateViewController ("accountSettingsController");
				this.NavigationController.PushViewController(accSettings, true);
			};


		}
	}
}
