// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using SportNet.Web.Models;

namespace SportNet
{
	public partial class NewsDetailController : UIViewController
	{
		public NewsDetailController (IntPtr handle) : base (handle)
		{
		}

		public NewsCellModel Data { get; set; }

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			this.Heading.Text = Data.Heading;
			this.Heading.SizeToFit ();
			this.Title = Data.Category;
			this.Image.Image = UIImage.FromFile (Data.ImageSource);
			this.Image.ContentMode = UIViewContentMode.ScaleAspectFill;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);

			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
		}
	}
}
