// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class PicturesController : UITableViewController
	{
		public PicturesController (IntPtr handle) : base (handle)
		{
		}
		public PicturesController ()
		{

		}
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			var article = new PicturesCellModel[] {
				new PicturesCellModel { Heading = "Maria was sent out of Wimbledon by a Portuguese player ranked 131 in the world", Category = "Formula 1",
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photo.png", PicturesCount = 17 },
				new PicturesCellModel { Heading = "Transfer news: Luis Suarez rocks Liverpool with news he will submit a transfer request ", Category = "Liverpool",
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photoSmall.png", PicturesCount = 17 },
				new PicturesCellModel { Heading = "Button: I haven't lost my enthusiasm", Category = "Formula 1",
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photoSmall.png", PicturesCount = 21 },
				new PicturesCellModel { Heading = "Hulkenberg vows to keep pushing", Category = "Sauber", 
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photoSmall.png", PicturesCount = 9 },
				new PicturesCellModel { Heading = "Button: I haven't lost my enthusiasm", Category = "Formula 1",
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photo.png", PicturesCount = 5 },
				new PicturesCellModel { Heading = "Cristiano Ronaldo", Category = "Football", 
					ImageSource = "./Assets/article-pic.jpg", PhotoSource = "./Assets/photoSmall.png", PicturesCount = 7 }
			};
			TableView.Source = new PicturesControllerSource (article);

			//this.TableView.Source = new PicturesControllerSource (article);
			//			TableView.SeparatorStyle = UITableViewCellSeparatorStyle.None;
			//			TableView.BackgroundColor = UIColor.Black;
			//this.TableView.ScrollsToTop = true;
		}
	}
}
