// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using SportNet.Web.Models;

namespace SportNet
{
	public partial class PicturesCollectionController : UICollectionViewController
	{
		public GalleryArticleModel Items { get; set; }
		public UIActivityIndicatorView Spinner { get; set; }

		public PicturesCollectionController (IntPtr handle) : base (handle)
		{
			Spinner = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge);
			Spinner.Center = new PointF (160, 160);
			Spinner.HidesWhenStopped = true;
			CollectionView.AddSubview (Spinner);
			Spinner.StartAnimating ();

			// lets fake a model here so the controller can initialize properly
			// we have a spinner view covering for us anyway and we will reload
			// the Items property as soon as the request is ready
			Items = new GalleryArticleModel ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			CollectionView.RegisterClassForCell (typeof(PictureCollectionCell), PictureCollectionCell.CellId);
			this.CollectionView.BackgroundColor = UIColor.FromRGB (26, 26, 26);
			this.CollectionView.AllowsMultipleSelection = false;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
		}

		public override UICollectionViewCell GetCell (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = (PictureCollectionCell)collectionView.DequeueReusableCell (PictureCollectionCell.CellId, indexPath);
			AppDelegate.MakeImageFromURL (cell.Image, Items.Images[indexPath.Row]);
			return cell;
		}

		public override UICollectionReusableView GetViewForSupplementaryElement (UICollectionView collectionView, NSString elementKind, NSIndexPath indexPath)
		{
			if (elementKind == (NSString)"UICollectionElementKindSectionHeader") {
				PictureHeaderVIew header = (PictureHeaderVIew)collectionView.DequeueReusableSupplementaryView 
					(UICollectionElementKindSection.Header, (NSString)"header", indexPath);
				header.title.Frame = new RectangleF (20, 15, 230, 300);
				header.title.Text = Items.Title;
				header.title.Lines = 0;
				header.title.SizeToFit ();
				header.photo.Image = UIImage.FromFile ("./Assets/photo.png");
				header.picturesCount.Text = Items.Images.Count.ToString();
				
				return header;
			} 
			else {
				StartReadingView footer = (StartReadingView)collectionView.DequeueReusableSupplementaryView 
					(UICollectionElementKindSection.Footer, (NSString)"collectionfooter", indexPath);
				footer.StartReading.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);
				footer.StartReading.TouchUpInside += (object sender, EventArgs e) => {
					UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);
					var prefs = (PreferencesSubController)board.InstantiateViewController ("preferencessub");
					this.NavigationController.PushViewController(prefs, true);
				};
				return footer;
			}
		}

		public override void ItemSelected (UICollectionView collectionView, NSIndexPath indexPath)
		{
			UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);
			PictureBigCollectionController bigPicture = (PictureBigCollectionController)board.InstantiateViewController ("pictureBigCollectionController");
			bigPicture.Title = string.Format ("{0}/{1}", indexPath.Row + 1, Items.Images.Count);
			bigPicture.Items = Items;
			bigPicture.StartingItem = indexPath.Row;
			((MainTabController)UIApplication.SharedApplication.Delegate.Window.RootViewController).
				Pictures.InternalTopNavigation.PushViewController (bigPicture,true);
		}

		public override int GetItemsCount (UICollectionView collectionView, int section)
		{
			return Items.Images.Count;
		}
	}
}
