// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;


namespace SportNet
{
	public partial class PictureBigCollectionController : UICollectionViewController
	{
		public string[] ImageSources { get; set; }

		public PictureBigCollectionController (IntPtr handle) : base (handle)
		{

		}
		public PictureBigCollectionController (UICollectionViewLayout layout){
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			CollectionView.RegisterClassForCell (typeof(PictureBigCollectionCell), PictureBigCollectionCell.CellId);
			this.CollectionView.BackgroundColor = UIColor.FromRGB (26, 26, 26);
			this.CollectionView.AllowsMultipleSelection = false;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;

		
		}

		public override UICollectionViewCell GetCell (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = (PictureBigCollectionCell)collectionView.DequeueReusableCell (PictureBigCollectionCell.CellId, indexPath);
			cell.Image = UIImage.FromFile ("./Assets/profilebig.png");
			return cell;
		}

		public override int GetItemsCount (UICollectionView collectionView, int section)
		{
			return ImageSources.Length;
		}

	}
}
