// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using System.Collections.Generic;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SportNet.Web.Models;
using Newtonsoft.Json;

namespace SportNet
{
	public partial class PicturesController : UITableViewController
	{
		private UIRefreshControl refresh;
		private UIActivityIndicatorView spinner;

		public UIActivityIndicatorView Spinner 
		{
			get {
				return spinner;
			}
		}

		public PicturesController (IntPtr handle) : base (handle)
		{
		}

		public PicturesController() 
		{
		}

		private void getData()
		{
			// load the articles and the menu from the server on a background thread
			var request = new RestRequest ();
			request.RequestFinished += (object sender, RequestEndedArgs e) => {
				InvokeOnMainThread(delegate {
					var data = (CategoryPicturesModel)JsonConvert.DeserializeObject(e.Result, typeof(CategoryPicturesModel));
					var menuController = (MenuController)((MainTabController)UIApplication.SharedApplication.Delegate.Window.RootViewController).Pictures.MenuViewLeft;

					// add 'all sports' item to the categories list
					if(data.Parent.Link == 0) {
						data.Categories.Insert(0, new CategoriesMenuModelItem { Name = "All Sports", Link = 0 });
					}
					else {
						data.Categories.Insert(0, new CategoriesMenuModelItem { Name = "Back" , Link = data.Parent.Link });
					}

					TableView.Source = new PicturesControllerSource(data.News, data.CategoryId);
					menuController.TableView.Source = new MenuControllerSource(data.Categories, "pictures");
					menuController.TableView.ReloadData();
					TableView.ReloadData();
					spinner.StopAnimating();
				});
			};
			request.Send (string.Format(RequestConfig.Pictures, 0, 0), "GET");
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			spinner = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge);
			spinner.Center = new PointF (160, 160);
			spinner.HidesWhenStopped = true;
			TableView.AddSubview (spinner);
			spinner.StartAnimating ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			refresh = new UIRefreshControl ();
			TableView.AddSubview (refresh);
			refresh.ValueChanged += (object sender, EventArgs e) => {
				getData();
				refresh.EndRefreshing();
			};

			TableView.ScrollsToTop = true;
			getData ();
		}
	}
}
