// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Newtonsoft.Json;
using SportNet.Web.Models;

namespace SportNet
{
	public partial class PreferencesSubController : UIViewController
	{
		private UIActivityIndicatorView spinner;

		public PreferencesSubController (IntPtr handle) : base (handle)
		{
		}

		public int CategoryId { get; set; }
		public bool ParentChecked { get; set; }

		public override void ViewWillAppear (bool animated)
		{
			spinner = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge);
			spinner.Center = new PointF (160, 160);
			spinner.HidesWhenStopped = true;
			View.AddSubview (spinner);
			spinner.StartAnimating ();
			TableView.Hidden = true;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;

			var request = new RestRequest ();
			request.RequestFinished += (object sender, RequestEndedArgs e) => {
				var data = (AddContentModel)JsonConvert.DeserializeObject(e.Result, typeof(AddContentModel));
				InvokeOnMainThread(delegate {
					AppDelegate.SubCategories = data;
					var all = new AddContentItem();
					all.Name = "All from " + data.ParentCategory.Name;
					all.HasChildren = false;
					all.Checked = ParentChecked;
					all.Id = data.ParentCategory.Id;
					AppDelegate.SubCategories.Categories.Insert(0, all);
					TableView.ReloadData();
					TableView.Hidden = false;
					spinner.StopAnimating();
				});
			};
			request.Send (string.Format(RequestConfig.SubCategories, CategoryId), "GET");

			this.TableView.Source = new PreferencesSubControllerSource ();
			this.TableView.AllowsMultipleSelection = true;
		}

	}
}
