// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class PreferencesController : UICollectionViewController
	{
		public string[] ImageSources { get; set; }

		public PreferencesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			CollectionView.RegisterClassForCell (typeof(PreferenceCell), PreferenceCell.CellId);
			this.CollectionView.BackgroundColor = UIColor.FromRGB (26, 26, 26);
			this.CollectionView.AllowsMultipleSelection = true;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
		}

		public override UICollectionViewCell GetCell (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = (PreferenceCell)collectionView.DequeueReusableCell (PreferenceCell.CellId, indexPath);
			cell.Image = UIImage.FromFile ("./Assets/category.png");
			return cell;
		}

		public override int GetItemsCount (UICollectionView collectionView, int section)
		{
			return ImageSources.Length;
		}

		public override UICollectionReusableView GetViewForSupplementaryElement (UICollectionView collectionView, NSString elementKind, NSIndexPath indexPath)
		{
			if (elementKind == (NSString)"UICollectionElementKindSectionHeader") {
				return (UICollectionReusableView)collectionView.DequeueReusableSupplementaryView 
					(UICollectionElementKindSection.Header, (NSString)"collectionheader", indexPath);
			} else {
				StartReadingView footer = (StartReadingView)collectionView.DequeueReusableSupplementaryView 
					(UICollectionElementKindSection.Footer, (NSString)"collectionfooter", indexPath);
				footer.StartReading.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);
				footer.StartReading.TouchUpInside += (object sender, EventArgs e) => {
					UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);
					var prefs = (PreferencesSubController)board.InstantiateViewController ("preferencessub");
					this.NavigationController.PushViewController(prefs, true);
				};
				return footer;
			}
		}

		public override void ItemSelected (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = (PreferenceCell)collectionView.CellForItem (indexPath);
			cell.Details.BackgroundColor = UIColor.FromRGBA (255, 0, 0, 200);
			cell.Indicator.Image = UIImage.FromFile ("./Assets/check.png");
		}

		public override void ItemDeselected (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = (PreferenceCell)collectionView.CellForItem (indexPath);
			cell.Details.BackgroundColor = UIColor.FromRGBA (0, 0, 0, 200);
			cell.Indicator.Image = UIImage.FromFile ("./Assets/plus.png");
		}
	}
}
