// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class PreferencesSubController : UIViewController
	{
		public PreferencesSubController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;

			this.Title = "Football";

			var leagues = new PreferenceModel[] {
				new PreferenceModel() { Title = "Select All", HasChild = false, Selected = false },
				new PreferenceModel() { Title = "Spain", HasChild = true, Selected = false },
				new PreferenceModel() { Title = "France", HasChild = false, Selected = false },
				new PreferenceModel() { Title = "Italy", HasChild = true, Selected = true },
				new PreferenceModel() { Title = "Spain", HasChild = true, Selected = true },
				new PreferenceModel() { Title = "France", HasChild = false, Selected = false },
				new PreferenceModel() { Title = "Italy", HasChild = true, Selected = false },
				new PreferenceModel() { Title = "Spain", HasChild = true, Selected = false },
				new PreferenceModel() { Title = "France", HasChild = false, Selected = false },
				new PreferenceModel() { Title = "Italy", HasChild = true, Selected = false },
				new PreferenceModel() { Title = "Spain", HasChild = true, Selected = false },
				new PreferenceModel() { Title = "France", HasChild = false, Selected = false },
				new PreferenceModel() { Title = "Italy", HasChild = true, Selected = false }
			};

			this.TableView.Source = new PreferencesSubControllerSource (leagues);
			this.TableView.AllowsMultipleSelection = true;
		}
	}
}
