// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;

namespace SportNet
{
	public partial class SignUpController : UIViewController
	{
		public SignUpController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			this.Image.Image = UIImage.FromFile ("./Assets/profilebig.png");
			this.ImagePicker.SetBackgroundImage (UIImage.FromFile ("./Assets/choose.png"), UIControlState.Normal);
			this.FirstName.Background = UIImage.FromFile ("./Assets/input.png");
			this.FirstName.TextColor = UIColor.FromRGB (102, 102, 102);
			this.LastName.Background = UIImage.FromFile ("./Assets/input.png");
			this.Email.Background = UIImage.FromFile ("./Assets/input.png");
			this.Password.Background = UIImage.FromFile ("./Assets/input.png");
			this.CreateAccount.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlong.png"), UIControlState.Normal);
			this.Facebook.SetBackgroundImage (UIImage.FromFile ("./Assets/facebook.png"), UIControlState.Normal);
			this.Twitter.SetBackgroundImage (UIImage.FromFile ("./Assets/twitter.png"), UIControlState.Normal);
			this.GooglePlus.SetBackgroundImage (UIImage.FromFile ("./Assets/google.png"), UIControlState.Normal);

			// hack the textfields to add padding
			// apparently this is not so easy in ios
			this.FirstName.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.FirstName.LeftViewMode = UITextFieldViewMode.Always;
			this.LastName.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.LastName.LeftViewMode = UITextFieldViewMode.Always;
			this.Email.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.Email.LeftViewMode = UITextFieldViewMode.Always;
			this.Password.LeftView = new UIView (new RectangleF (0, 0, 5, 30));
			this.Password.LeftViewMode = UITextFieldViewMode.Always;

			var button = new UIBarButtonItem ("Back", UIBarButtonItemStyle.Plain, null);
			var custom = new UIButton (new RectangleF (0, 0, 26, 15));
			custom.SetBackgroundImage(UIImage.FromFile("./Assets/back.png"), UIControlState.Normal);
			custom.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated (true);
			button.CustomView = custom;

			this.NavigationItem.LeftBarButtonItem = button;
			this.NavigationController.SetNavigationBarHidden (false, false);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.CreateAccount.TouchUpInside += (object sender, EventArgs e) => {
				UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);
				PreferencesController welcome = (PreferencesController)board.InstantiateViewController ("preferencescontroller");
				welcome.ImageSources = new string[] { "aaa", "a", "a", "a", "a", "a", "a", "a", "a" };

				this.NavigationController.PushViewController(welcome, true);
			};
		}
	}
}
