// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class StartReadingView : UICollectionReusableView
	{
		public StartReadingView (IntPtr handle) : base (handle)
		{
		}
	}
}
