// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SportNet
{
	public partial class WelcomeController : UIViewController
	{
		public WelcomeController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.BackgroundView.Image = UIImage.FromFile ("./Assets/wall.png");
			this.Login.SetBackgroundImage (UIImage.FromFile ("./Assets/buttonlongwhite.png"), UIControlState.Normal);
			this.Register.SetBackgroundImage(UIImage.FromFile("./Assets/buttonlong.png"), UIControlState.Normal);

			this.NavigationController.SetNavigationBarHidden (true, false);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			AppDelegate appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;
			UIStoryboard board = UIStoryboard.FromName ("MainStoryboard", null);

			this.Login.TouchUpInside += (object sender, EventArgs e) => {
				LoginController login = (LoginController)board.InstantiateViewController ("logincontroller");
				this.NavigationController.PushViewController(login, true);
			};

			this.Register.TouchUpInside += (object sender, EventArgs e) => {
				SignUpController signUp = (SignUpController)board.InstantiateViewController ("signupcontroller");
				this.NavigationController.PushViewController(signUp, true);
			};
		}
	}
}
